name: s5gydl kata 自动续期任务

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "任务开始"

      - name: Run actions/checkout@v5
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          always-auth: false
          check-latest: false

      - name: Install Dependencies
        run: npm install

      - name: Run Renew Script
        env:
          USERS_JSON: ${{ secrets.USERS_JSON }}
          PROXY_URL: ${{ secrets.PROXY_URL }}
          SUB_URL: ${{ secrets.SUB_URL }}
          S5_URL: ${{ secrets.S5_URL }}
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TG_THREAD_ID: ${{ secrets.TG_THREAD_ID }}
          DEBUG_SCREENSHOT: true
          DEBUG: true
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" node kata_renew.js

      - name: Commit Renew Dates
        continue-on-error: true
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add renew_dates.json || true
          git diff --cached --quiet renew_dates.json || git commit -m "chore: update renew dates" renew_dates.json
          for i in {1..5}; do
            git pull --rebase --autostash || true
            if git push; then
              break
            fi
            sleep 5
          done
        shell: /usr/bin/bash -e

      - name: Upload Screenshots
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: screenshots
          path: screenshots/
